//Para rodar CTR+ALT+S

//Assinar com private key

POST http://localhost:3000/user/sign-transaction 
content-type: application/json

{
    "keyType": "privateKey",
    "privateKey": "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d",
    "tx": {
      "nonce": 1,
      "chainId": "0xMinhaChain",
      "to": "user-123",
      "mensagem": "hello"
    }
  }

###

//Verifica Assinatura

POST http://localhost:3000/user/verify-signature
content-type: application/json

{
    "tx": {
      "nonce": 1,
      "chainId": "0xMinhaChain",
      "to": "user-123",
      "mensagem": "hello"
    },
    "signature": "0x9a10b928e05c340c7821c36dcb588831564fb8ea825597f786fceff1c97665562af88f52b05e52ce83374db229006c3d2e3101fcf085081865670e1538befd721c",
    "expectedFrom": "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
  }

  ###